spring.application.name=initilance
spring.datasource.url=jdbc:postgresql://localhost:5432/initlance_db
spring.datasource.username=postgres
spring.datasource.password=amandaebea
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#admin  #Substitua "admin" pela senha do seu banco de dados e apague esse comentario